CREATE TABLE cart
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    VARCHAR(255),
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_items
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    cart_id    INTEGER                                  NOT NULL,
    product_id INTEGER                                  NOT NULL,
    user_id    VARCHAR(255)                             NOT NULL,
    quantity   INTEGER                                  NOT NULL,
    price      DOUBLE PRECISION                         NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id INTEGER                                 NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    status            VARCHAR(255)                            NOT NULL,
    alamat_pengiriman VARCHAR(255)                            NOT NULL,
    nama_penerima     VARCHAR(255)                            NOT NULL,
    shipment_id       BIGINT,
    payment_id        BIGINT,
    voucher_id        VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    user_id        VARCHAR(255)                            NOT NULL,
    total_price    DECIMAL                                 NOT NULL,
    payment_status VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    paid_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name        VARCHAR(256)                             NOT NULL,
    product_price       INTEGER                                  NOT NULL,
    product_stock       INTEGER                                  NOT NULL,
    product_discount    INTEGER,
    product_description VARCHAR(512)                             NOT NULL,
    product_image       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE shipments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id        BIGINT                                  NOT NULL,
    shipment_method VARCHAR(255)                            NOT NULL,
    tracking_number VARCHAR(16)                             NOT NULL,
    shipment_status VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_shipments PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_products_product_name UNIQUE (product_name);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_SHIPMENT FOREIGN KEY (shipment_id) REFERENCES shipments (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);