CREATE TABLE product_images
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255) NOT NULL,
    product_id INTEGER,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE products
    ADD product_image VARCHAR(255);

ALTER TABLE products
    ALTER COLUMN product_image SET NOT NULL;

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (product_id);