ALTER TABLE product_images
    DROP CONSTRAINT fk_product_images_on_product;

CREATE TABLE cart_items
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    quantity   INTEGER NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

ALTER TABLE cart_items
    ADD CONSTRAINT FK_CART_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (product_id);

DROP TABLE product_images CASCADE;